language: python
python:
  - "3.6"
env:
  - MONGODB_URI=mongodb://travis:password@localhost:27017/database
services:
  - mongodb
install:
  - pip install -r requirements.txt
before_script:
  - sleep 15
  - mongo database --eval 'db.createUser({user:"travis",pwd:"password",roles:["readWrite"]});'
script:
  - python -m unittest discover -s tests
  - python -m unittest discover -s tests -p it*.py
branches:
  only:
  - master
